import start from "../content/00-start-here.md?raw";
import basics from "../content/01-language-model-basics.md?raw";
import attention from "../content/02-attention-transformer.md?raw";
import architecture from "../content/03-architecture-evolution.md?raw";
import pretraining from "../content/04-pretraining-scaling-data.md?raw";
import postTraining from "../content/05-post-training-alignment.md?raw";
import fineTuning from "../content/06-fine-tuning-peft.md?raw";
import quantization from "../content/07-quantization-compression.md?raw";
import inference from "../content/08-inference-efficiency-mtp.md?raw";
import reasoning from "../content/09-reasoning-test-time-compute.md?raw";
import systems from "../content/10-multimodal-rag-agents.md?raw";
import evaluation from "../content/11-evaluation-safety-interpretability.md?raw";
import families from "../content/12-model-families.md?raw";
import timeline from "../content/13-timeline.md?raw";
import research from "../content/14-research-roadmap.md?raw";
import glossary from "../content/15-glossary.md?raw";
import audit from "../content/16-search-audit.md?raw";

export type Chapter = {
  slug:string; number:string; title:string; description:string; level:string; section:string; content:string;
  video:{ title:string; duration:string; note:string; url:string; embedId?:string };
};

export const chapters: Chapter[] = [
  { slug:"start", number:"00", title:"Start here", description:"The field in one mental model and a practical learning route.", level:"Beginner", section:"Foundations", content:start, video:{title:"But what is a GPT?", duration:"13 min", note:"A visual map of the ideas you will meet in this guide.", url:"https://www.youtube.com/watch?v=wjZofJX0v4M", embedId:"wjZofJX0v4M"} },
  { slug:"language-models", number:"01", title:"Language models from zero", description:"Tokens, vectors, probability, loss, and generation.", level:"Beginner", section:"Foundations", content:basics, video:{title:"Neural networks, from scratch", duration:"19 min", note:"Build the intuition for parameters, vectors, and learned representations.", url:"https://www.youtube.com/watch?v=aircAruvnKk", embedId:"aircAruvnKk"} },
  { slug:"transformer", number:"02", title:"Attention & the Transformer", description:"Q, K, V, heads, blocks, position, and the forward pass.", level:"Core", section:"Foundations", content:attention, video:{title:"Attention in transformers, step by step", duration:"18 min", note:"A visual walkthrough of queries, keys, values, and attention patterns.", url:"https://www.youtube.com/watch?v=eMlx5fFNoYc", embedId:"eMlx5fFNoYc"} },
  { slug:"architecture", number:"03", title:"Architecture evolution", description:"From 2017 attention to MoE, multimodality, and state-space models.", level:"Core", section:"Architecture", content:architecture, video:{title:"A visual intro to transformers", duration:"13 min", note:"Use this as the compact bridge from the original Transformer to today’s systems.", url:"https://www.youtube.com/watch?v=wjZofJX0v4M", embedId:"wjZofJX0v4M"} },
  { slug:"pretraining", number:"04", title:"Pretraining, scaling & data", description:"Objectives, data pipelines, scaling laws, and distributed training.", level:"Core", section:"Training", content:pretraining, video:{title:"Gradient descent, visually explained", duration:"21 min", note:"See how repeated prediction errors become useful model parameters.", url:"https://www.youtube.com/watch?v=IHZwWFHWa-w", embedId:"IHZwWFHWa-w"} },
  { slug:"post-training", number:"05", title:"Post-training & alignment", description:"SFT, RLHF, DPO, RLAIF, GRPO, verification, and distillation.", level:"Advanced", section:"Training", content:postTraining, video:{title:"RLHF and preference tuning", duration:"8 min", note:"A short companion for the shift from raw next-token prediction to helpful behavior.", url:"https://www.youtube.com/results?search_query=RLHF+preference+alignment+explained"} },
  { slug:"fine-tuning", number:"06", title:"Fine-tuning & PEFT", description:"Full adaptation, LoRA, QLoRA, datasets, merging, and evaluation.", level:"Applied", section:"Training", content:fineTuning, video:{title:"LoRA and QLoRA in plain English", duration:"10 min", note:"Watch for the low-rank update intuition before reading the implementation details.", url:"https://www.youtube.com/results?search_query=LoRA+QLoRA+explained"} },
  { slug:"quantization", number:"07", title:"Quantization & compression", description:"Low precision, GPTQ, AWQ, SmoothQuant, pruning, and trade-offs.", level:"Applied", section:"Efficiency", content:quantization, video:{title:"What is LLM quantization?", duration:"9 min", note:"A focused introduction to lower precision, memory savings, and accuracy trade-offs.", url:"https://www.youtube.com/watch?v=VVFscAMihHA", embedId:"VVFscAMihHA"} },
  { slug:"inference", number:"08", title:"Inference, serving & MTP", description:"KV caches, kernels, batching, speculative decoding, and multi-token prediction.", level:"Advanced", section:"Efficiency", content:inference, video:{title:"How LLM inference gets faster", duration:"11 min", note:"Keep this open while you compare prefill, decode, caching, and batching.", url:"https://www.youtube.com/results?search_query=LLM+inference+KV+cache+speculative+decoding+explained"} },
  { slug:"reasoning", number:"09", title:"Reasoning & test-time compute", description:"CoT, search, verifiers, reasoning RL, and faithful evaluation.", level:"Advanced", section:"Frontier", content:reasoning, video:{title:"How reasoning models use more compute", duration:"12 min", note:"A short orientation to search, sampling, and inference-time scaling.", url:"https://www.youtube.com/results?search_query=reasoning+models+test-time+compute+explained"} },
  { slug:"agents", number:"10", title:"Multimodality, RAG & agents", description:"Evidence, tools, memory, orchestration, and security boundaries.", level:"Applied", section:"Frontier", content:systems, video:{title:"RAG and AI agents, side by side", duration:"12 min", note:"Clarify the difference between retrieving evidence and taking actions with tools.", url:"https://www.youtube.com/results?search_query=RAG+AI+agents+explained"} },
  { slug:"evaluation", number:"11", title:"Evaluation, safety & interpretability", description:"Measure the right system, find failures, and study mechanisms.", level:"Research", section:"Frontier", content:evaluation, video:{title:"How to evaluate an AI system", duration:"10 min", note:"A practical primer on benchmarks, failure modes, and evaluation design.", url:"https://www.youtube.com/results?search_query=LLM+evaluation+safety+benchmarks+explained"} },
  { slug:"families", number:"12", title:"Five model ecosystems", description:"OpenAI, Google, Meta, Qwen, and DeepSeek—current through August 2026.", level:"Current", section:"Field map", content:families, video:{title:"The modern LLM landscape", duration:"14 min", note:"A quick visual reset before comparing the families and their design choices.", url:"https://www.youtube.com/results?search_query=large+language+model+landscape+OpenAI+Google+Meta+Qwen+DeepSeek"} },
  { slug:"timeline", number:"13", title:"2017–2026 timeline", description:"The milestones and terminology shifts that reorganized the field.", level:"Reference", section:"Field map", content:timeline, video:{title:"The Transformer revolution in one sitting", duration:"13 min", note:"Revisit the core breakthrough that anchors the timeline.", url:"https://www.youtube.com/watch?v=wjZofJX0v4M", embedId:"wjZofJX0v4M"} },
  { slug:"research", number:"14", title:"Research roadmap", description:"Competencies, reproduction ladder, open questions, and project design.", level:"Research", section:"Reference", content:research, video:{title:"How to read a machine learning paper", duration:"9 min", note:"A compact companion for turning papers into reproducible research questions.", url:"https://www.youtube.com/results?search_query=how+to+read+machine+learning+papers+research+workflow"} },
  { slug:"glossary", number:"15", title:"Glossary", description:"Compact definitions for the field’s core language.", level:"Reference", section:"Reference", content:glossary, video:{title:"LLM terms in under 15 minutes", duration:"15 min", note:"Use this as a visual refresher when a definition in the glossary feels abstract.", url:"https://www.youtube.com/results?search_query=large+language+model+glossary+terms+explained"} },
  { slug:"audit", number:"16", title:"Research audit", description:"Search queries, coverage, evidence policy, and limitations.", level:"Methods", section:"Reference", content:audit, video:{title:"A practical guide to research quality", duration:"10 min", note:"A short reminder to separate evidence, uncertainty, and claims.", url:"https://www.youtube.com/results?search_query=how+to+evaluate+AI+research+claims+evidence"} },
];
