import type { Video } from "./chapters";

// Embed the search itself so the card still has a playable video and thumbnail;
// the source link exposes the full result set for readers who want to compare.
const find = (title:string, duration:string, note:string, query:string): Video => ({
  title,
  duration,
  note,
  url:`https://www.youtube.com/results?search_query=${query}`,
  embedUrl:`https://www.youtube-nocookie.com/embed?listType=search&list=${query}`,
});
const watch = (title:string, duration:string, note:string, id:string): Video => ({title,duration,note,url:`https://www.youtube.com/watch?v=${id}`,embedId:id});

// Exact Markdown subtitle slugs. Missing keys intentionally mean no video.
export const chapterVideos: Record<string, Record<string, Video[]>> = {
  start:{"the-entire-field-in-one-paragraph":[watch("But what is a GPT?","13 min","A visual map of the ideas in this guide.","wjZofJX0v4M")]},
  "language-models":{"text-becomes-tokens":[find("How tokenization works","7 min","See how text becomes discrete IDs.","LLM+tokenization+tokens+explained")],"ids-become-vectors":[watch("Neural networks, from scratch","19 min","Build intuition for parameters and representations.","aircAruvnKk")],"the-objective":[find("Next-token prediction and cross entropy","9 min","Connect the training objective to probability.","next+token+prediction+cross+entropy+explained")],sampling:[find("How language-model sampling works","8 min","A focused look at temperature and probability.","language+model+sampling+temperature+explained")]},
  transformer:{"why-attention-mattered":[watch("Attention in transformers, step by step","18 min","A visual walkthrough of information routing.","eMlx5fFNoYc")],"query-key-value":[find("Query, key, value attention","8 min","See the three roles in attention.","query+key+value+attention+transformer+explained")],"self-attention-and-masks":[find("Self-attention and causal masks","9 min","Understand how decoders hide future tokens.","self+attention+causal+mask+transformer")],"multi-head-attention":[find("Multi-head attention visually","8 min","See how heads specialize in parallel.","multi+head+attention+explained+visual")]},
  architecture:{"2017–2019-pretraining-becomes-the-interface":[find("Transformer history BERT GPT","11 min","The shift that made pretraining the interface.","2017+Transformer+BERT+GPT+architecture+history")],"2024–2026-multimodal-moe-reasoning-and-action":[find("Mixture of experts and multimodal models","12 min","A bridge to MoE, multimodality, and action.","mixture+of+experts+multimodal+reasoning+models+explained")]},
  pretraining:{"pretraining-is-compression-through-prediction":[find("How LLM pretraining works","10 min","See pretraining as compression through prediction.","large+language+model+pretraining+explained")],"scaling-laws":[find("Scaling laws for language models","9 min","Why data, parameters, and compute move together.","LLM+scaling+laws+parameters+data+compute")],"optimization-concepts":[watch("Gradient descent, visually explained","21 min","See how prediction errors become parameters.","IHZwWFHWa-w")]},
  "post-training":{"stage-1-supervised-fine-tuning-sft":[find("Supervised fine-tuning SFT","8 min","The first post-training step: demonstrations.","supervised+fine+tuning+SFT+explained")],preferences:[find("RLHF human preferences","9 min","How preference data changes optimization.","RLHF+human+preference+data+explained")],"dpo-and-related-objectives":[find("Direct preference optimization DPO","9 min","A focused companion to the DPO objective.","direct+preference+optimization+DPO+explained")],"rl-with-verifiable-rewards":[find("Reinforcement learning with verifiable rewards","10 min","Why checkable outcomes create a new signal.","reinforcement+learning+verifiable+rewards+LLM")]},
  "fine-tuning":{lora:[find("LoRA low-rank adaptation","9 min","Visualize the small trainable update.","LoRA+low+rank+adaptation+explained")],qlora:[find("QLoRA 4-bit fine-tuning","9 min","Connect quantization with adapters.","QLoRA+4-bit+fine+tuning+explained")],"dataset-design":[find("Fine-tuning dataset design","10 min","Examples, quality, coverage, and leakage.","LLM+fine+tuning+dataset+design+quality")]},
  quantization:{"precision-is-a-systems-choice":[find("What is LLM quantization?","9 min","Lower precision, memory, and accuracy trade-offs.","LLM+quantization+precision+memory+explained")],"ptq-vs-qat":[find("PTQ versus QAT","9 min","Compare rounding and calibration.","PTQ+versus+QAT+quantization+explained")],"major-methods":[find("GPTQ AWQ SmoothQuant","11 min","Compare the main quantization families.","GPTQ+AWQ+SmoothQuant+explained")]},
  inference:{"prefill-and-decode":[find("LLM prefill and decode","8 min","Separate prompt processing from decode.","LLM+prefill+decode+explained")],"the-kv-cache":[find("KV cache in transformers","9 min","Why serving keeps prior keys and values.","transformer+KV+cache+explained")],"speculative-decoding":[find("Speculative decoding","9 min","How a draft model accelerates a larger one.","speculative+decoding+large+language+models")]},
  reasoning:{"chain-of-thought-prompting":[find("Chain-of-thought prompting","8 min","The prompting pattern and its limits.","chain+of+thought+prompting+explained")],"sampling-and-search":[find("LLM sampling and search","10 min","Compare candidates, search, and selection.","LLM+sampling+search+reasoning+explained")],"inference-time-scaling":[find("Inference-time scaling","10 min","Trading latency for harder problem solving.","inference-time+scaling+reasoning+models")]},
  agents:{"retrieval-augmented-generation-rag":[find("Retrieval augmented generation RAG","10 min","How evidence retrieval wraps a model.","retrieval+augmented+generation+RAG+explained")],tools:[find("LLM tool use and function calling","9 min","How a model calls external capabilities.","LLM+tool+use+function+calling+explained")],agents:[find("AI agents planning tools memory","11 min","A concrete model–tool loop.","AI+agents+planning+tools+memory+explained")]},
  evaluation:{"start-from-a-threat-model-and-use-case":[find("AI threat modeling and safety evaluation","10 min","Start with the failure that matters.","AI+threat+modeling+safety+evaluation+explained")],"evaluation-layers":[find("LLM evaluation layers","9 min","Separate component, behavior, system, and impact.","LLM+evaluation+layers+capability+behavior+system")],"benchmark-hazards":[find("AI benchmark contamination and saturation","9 min","Why benchmarks can mislead.","AI+benchmark+hazards+contamination+leakage")]},
  research:{"how-to-read-a-paper":[find("How to read a machine learning paper","9 min","Turn papers into reproducible questions.","how+to+read+machine+learning+papers+research+workflow")]},
};

const urls = Object.values(chapterVideos).flatMap((headings) => Object.values(headings).flatMap((videos) => videos.map((video) => video.url)));
if (new Set(urls).size !== urls.length) throw new Error("Duplicate YouTube video assignment in chapterVideos");
